name: "Baseruby"

on:
  - "push"
  - "workflow_dispatch"

jobs:
  set-matrix:
    runs-on: "ubuntu-latest"
    outputs:
      ruby: "${{ steps.set-matrix.outputs.ruby }}"
    container:
      image: "ruby:3.1-alpine"
    steps:
      - uses: "actions/checkout@v3"

      - id: "set-matrix"
        run: |
          matrix="$(ruby -ryaml -rjson -e 'puts YAML.load_file("matrix.yml")["ruby"].to_json')"
          echo "ruby=$matrix" >> $GITHUB_OUTPUT

  build:
    needs: "set-matrix"
    name: "Ruby ${{ matrix.ruby.slug }} on ${{ matrix.platform }}"
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        platform:
          - "linux/amd64"
          - "linux/arm64"
        ruby: ${{ fromJson(needs.set-matrix.outputs.ruby) }}
    steps:
      - uses: "actions/checkout@v3"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ matrix.platform }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./docker/builds/baseruby
          platforms: ${{ matrix.platform }}
          tags: |
            ghcr.io/oxidize-rb/rubies:${{ matrix.ruby.slug }}
            ghcr.io/oxidize-rb/rubies:${{ matrix.ruby.version }}
          build-args: |
            RUBY_VERSION="${{ matrix.ruby.version }}"
            RUBY_MINOR="${{ matrix.ruby.minor }}"
            RUBY_SHA256="${{ matrix.ruby.sha256 }}"
